/*
Tasmanian Strategical
Copyright (C) 1993, 1994, 2019 Laurence Maar

laurencemaar@gmail.com
https://www.facebook.com/laurencemaar/
https://www.linkedin.com/in/laurencemaar/
https://github.com/laurencemaar/
https://sourceforge.net/u/laurencemaar/

-----

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/* Tasmanian Strategical - Notepad ------------------------------------------

  o Create message base
  o Make F2 Viewing option if possible for future purposes

------------------------------------------- Tasmanian Strategical - Notepad */
/*
void population(void){}

void invest(void){}

void centre(void){}

void news(void){}

void abdicate(void){}

void displaymenu(void){}

void lastquote(void){}

void wrong(void){}

void notdone(void){}

void mustregister(void){}

void registerme(void){}

void corrupt(void){}

void displayrelations(int mod){if(mod)return;}

void __MNT__main(void){}

void __PCB__main(void){}
*/
