/*
Tasmanian Strategical
Copyright (C) 1993, 1994, 2019 Laurence Maar

laurencemaar@gmail.com
https://www.facebook.com/laurencemaar/
https://www.linkedin.com/in/laurencemaar/
https://github.com/laurencemaar/
https://sourceforge.net/u/laurencemaar/

-----

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

char programname[4]=    "T-S"   ;
char filename[4]=       "TAZ"   ;
char fullname[22]=      "Tasmanian Strategical";
char __author[15]=      "Laurence Maar";
char __version[5]=	"1.03"	;
char __vspace[5]=	"   "	;
char __saveversion[5]=	"0101"	;
char __vnew[5]=		"0.90"	;
char __vnewsp[5]=	""	;
char __vday[5]=		"0.90"	;
char __vdaysp[5]=	""	;
char __vcnv[5]=		"0.90"	;
char __vcnvsp[5]=	""	;
char __vkey[5]=		"1.0"	;
char __vkeysp[5]=	" "	;
char __vlog[5]=		"1.0"	;
char __vlogsp[5]=	" "	;
char __vset[5]=		"1.00"	;
char __vsetsp[5]=	""	;
char __REGFILE__[11]="TAZREG.NFO";
char __DATFILE__[11]="TAZDAT.NFO";
char __DXXFILE__[11]="TAZDXX.NFO";
char __DYYFILE__[11]="TAZDYY.NFO";
char __BKDFILE__[11]="TAZBKD.NFO";
char __LNGFILE__[11]="TAZLNG.NFO";
char __FRNFILE__[11]="TAZFRN.NFO";
char __CFGFILE__[11]="TAZCFG.NFO";
char __SPCFILE__[11]="TAZSPC.NFO";
char __SYNFILE__[11]="TAZSYN.NFO";

//char __TITLE__  [2][13]={"MAAR-ANS.NFO","MAAR-ASC.NFO"};
  char __TITLE1__ [2][13]={"MAARTIAN.NFO","OMNICRON.NFO"};
  char __TITLE2__ [2][13]={"TAZNET.NFO",  "TAZNEW.NFO"  };

char __SAVFILE__[10][11]={"TAZSA0.DAT","TAZSA1.DAT","TAZSA2.DAT","TAZSA3.DAT",
"TAZSA4.DAT","TAZSA5.DAT","TAZSA6.DAT","TAZSA7.DAT","TAZSA8.DAT","TAZSA9.DAT"};
char __WARFILE__[11]="TAZWAR.DAT";
char __LOGFILE__[11]="TAZLOG.DAT";
